### ISSUE TITLE
Sites that aren't proxied with Edgecast fail CI

### ISSUE THREAD

**Issue by pushred** [SparkartGroupInc/broadway#21]
https://github.com/SparkartGroupInc/broadway/pull/16 added an Edgecast purge request to the end of the deployment process, but for any sites that aren't proxied by Edgecast this causes a fatal error:

```
Notifying webhook: https://api.edgecast.com/v2/mcc/customers/08DF/edge/purge

Error: {"Message":"Invalid strPath parameter.  Please double check the path to make sure it is valid.  Also check that the media type id represents the correct platform for the path given."}
    at Request._callback (/home/ubuntu/sparkart-services-docs/node_modules/broadway/node_modules/qa-deployer/src/utils/json-request.js:25:13)
    at Request.self.callback (/home/ubuntu/sparkart-services-docs/node_modules/broadway/node_modules/qa-deployer/node_modules/request/request.js:122:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/ubuntu/sparkart-services-docs/node_modules/broadway/node_modules/qa-deployer/node_modules/request/request.js:888:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/ubuntu/sparkart-services-docs/node_modules/broadway/node_modules/qa-deployer/node_modules/request/request.js:839:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
```

These sites are in the minority, i.e. docs.services.sparkart.net. We could add an option or a separate deploy script that omits this addition to use, but perhaps returning a warning vs. an error would be simpler.

**Comment by joanniclaborde** [comment]
Or, remove the `EDGECAST_API_TOKEN` environment variable from CircleCI for those sites: https://github.com/SparkartGroupInc/broadway/blob/master/config/deploy-production.js#L17

**Comment by joanniclaborde** [comment]
Reopen if needed!
